site_name: Jéssica Gontijo ○ Naturologia e Ayurveda
site_url: https://jessicagontijo.com
site_description: Tratamento natural para sintomas do climatério e menopausa. Utilize a medicina ayurveda e práticas integrativas para recuperar equilíbrio, bem-estar e qualidade de vida.

theme:
  name: material
  language: pt-BR
  palette:
    # Paleta principal (clara)
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    # Paleta escura (opcional)
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  
  font:
    text: PT Serif
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.integrate

  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: pt

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/5531992922463
      name: WhatsApp
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/jessicagontijo.naturologia
      name: Instagram
  
  analytics:
    provider: google
    property: G-FZ711LHTKY

copyright: |
  &copy; 2024 <strong>Jéssica Gontijo</strong> - Naturologia e Ayurveda<br>
  Registro ABRANA: 100443 | CBO: 2263-20

nav:
  - Início: index.md
